name: Test running shared workflow
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - run: |
          echo "-------------------"
  
