name: Check out and cache 
on:
  workflow_call:
    inputs:
      working-directory:
        description: The directory to checkout
        required: true
        type: string
    outputs:
      git-sha:
        description: The SHA of the commit that triggered the workflow
        value: ${{ jobs.checkout-and-cache.outputs.sha }}
      git-branch:
        description: The branch that triggered the workflow
        value: ${{ jobs.checkout-and-cache.outputs.branch }}
jobs:
  checkout-and-cache:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      branch: ${{ steps.vars.outputs.branch }}
    steps:
      - run: echo $${{ inputs.working-directory }}

      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci
      - name: Detect Environment
        working-directory: ${{ inputs.working-directory }}
        id: vars 
        shell: bash
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
