name: Test project
on: push
env:
  DISABLE_WORKFLOW: true
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample

    if: env.DISABLE_WORKFLOW != 'true'
    
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo Deploy
